---
name: Yaml Lint Per File

on:
  push:
    branches:
      - master
      - jackett-pulls
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yamllint version
        run: |
          yamllint --version
      - name: yamllint run
        run: |
          for f in `find definitions -type f`
          do
            echo "$f"
            yamllint "$f" --format github
          done
